import { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/v1';
interface Field { key: string; label: string; value: string | number | boolean | null; source?: string; }
interface Document { id: string; document_type: string; status: string; extracted_record: { party_name: string | null; fields: Field[] } | null; }
const typeLabel: Record<string, string> = { auto_policy: 'Auto policy', home_policy: 'Home policy', life_insurance: 'Life insurance', warranty: 'Warranty', tax: 'Tax document', receipt: 'Receipt', other: 'Document' };
function valueFor(value: Field['value']) { if (value === null) return 'Not available'; if (typeof value === 'boolean') return value ? 'Yes' : 'No'; return String(value); }
export function DocumentDetail({ documentId, onBack }: { documentId: string; onBack: () => void }) { const { token } = useAuth(); const [document, setDocument] = useState<Document | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void load(); }, [documentId, token]); async function load() { try { const response = await fetch(`${API_BASE_URL}/documents/${documentId}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(); setDocument(await response.json()); } catch { setError('We could not load this document.'); } }
  async function download() { try { const response = await fetch(`${API_BASE_URL}/documents/${documentId}/download`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(); const url = URL.createObjectURL(await response.blob()); const link = window.document.createElement('a'); link.href = url; link.download = 'kanak-document.pdf'; link.click(); URL.revokeObjectURL(url); } catch { setError('The original PDF could not be downloaded.'); } }
  if (error) return <main className="page-content"><button className="back-link" onClick={onBack}>← Back to Vault</button><div className="notice error">{error}</div></main>;
  if (!document) return <main className="page-content"><p className="status-message">Loading document…</p></main>;
  const title = `${typeLabel[document.document_type] ?? 'Document'}${document.extracted_record?.party_name ? ` · ${document.extracted_record.party_name}` : ''}`;
  return <main className="page-content narrow"><button className="back-link" onClick={onBack}>← Back to Vault</button><header className="detail-heading"><p className="eyebrow">Document details</p><div><h1>{title}</h1><span className={`status-pill ${document.status}`}>{document.status === 'ready' ? 'Ready' : 'Processing'}</span></div><p className="page-subtitle">Details extracted from your original document.</p></header><section className="field-list">{document.extracted_record?.fields?.map((field) => <article className="field-card" key={field.key}><span className="field-symbol">▤</span><div><p>{field.label}</p><strong>{valueFor(field.value)}</strong><small>{field.source || 'From document'}</small></div></article>) ?? <p className="status-message">Your document is being processed. Check back shortly.</p>}</section><div className="detail-actions"><button className="button secondary" onClick={() => void download()}>Open original PDF</button>{['auto_policy', 'home_policy'].includes(document.document_type) && <button className="button primary" type="button">Compare rates</button>}</div></main>; }
