import { useState, type FormEvent } from 'react';
import { useAuth } from '../contexts/AuthContext';
type Channel = 'email' | 'phone';
export function SignIn() { const { startEmailAuth, verifyEmailAuth, startPhoneAuth, verifyPhoneAuth, signInWithApple } = useAuth(); const [channel, setChannel] = useState<Channel>('email'); const [step, setStep] = useState<'identity' | 'otp'>('identity'); const [identity, setIdentity] = useState(''); const [code, setCode] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function start(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { channel === 'email' ? await startEmailAuth(identity) : await startPhoneAuth(identity); setStep('otp'); } catch (err) { setError(err instanceof Error ? err.message : 'We could not send a code.'); } finally { setLoading(false); } }
  async function verify(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { channel === 'email' ? await verifyEmailAuth(identity, code) : await verifyPhoneAuth(identity, code); } catch (err) { setError(err instanceof Error ? err.message : 'That code did not work.'); setLoading(false); } }
  async function apple() { setLoading(true); setError(null); try { await signInWithApple(); } catch (err) { setError(err instanceof Error ? err.message : 'Apple sign-in is unavailable.'); setLoading(false); } }
  const label = channel === 'email' ? 'Email address' : 'Mobile number'; const description = channel === 'email' ? 'We’ll send a one-time code to your email. No password needed.' : 'We’ll text a one-time code to your phone. No password needed.';
  const appleButton = <button className="button apple-button full" type="button" disabled={loading} onClick={() => void apple()}> Continue with Apple</button>;
  return <main className="sign-in-page"><div className="sign-in-intro"><div className="brand"><span className="brand-mark">K</span><span>Kanak AI</span></div><h1>Life’s details, handled.</h1><p>Your trusted account-keeper for the documents, renewals, and decisions that matter.</p></div><section className="sign-in-card"><p className="eyebrow">Welcome</p><h2>{step === 'identity' ? 'Sign in to Kanak AI' : 'Enter your code'}</h2><p className="card-copy">{step === 'identity' ? description : `We sent a six-digit code to ${identity}.`}</p>{error && <div className="notice error">{error}</div>}{step === 'identity' ? <><div className="auth-tabs"><button className={channel === 'email' ? 'active' : ''} onClick={() => { setChannel('email'); setIdentity(''); }}>Email</button><button className={channel === 'phone' ? 'active' : ''} onClick={() => { setChannel('phone'); setIdentity(''); }}>Phone</button></div><form onSubmit={(event) => void start(event)}><label>{label}<input type={channel === 'email' ? 'email' : 'tel'} value={identity} onChange={(event) => setIdentity(event.target.value)} placeholder={channel === 'email' ? 'you@example.com' : '+15551234567'} autoComplete={channel === 'email' ? 'email' : 'tel'} required disabled={loading} /></label><button className="button primary full" disabled={loading}>{loading ? 'Sending…' : 'Send code'}</button></form><div className="auth-divider"><span>or</span></div>{appleButton}</> : <><form onSubmit={(event) => void verify(event)}><label>Verification code<input className="otp-input" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" required /></label><button className="button primary full" disabled={loading || code.length !== 6}>{loading ? 'Verifying…' : 'Verify and continue'}</button><button className="text-button center" type="button" onClick={() => { setStep('identity'); setCode(''); setError(null); }}>Use a different sign-in method</button></form><div className="auth-divider"><span>or</span></div>{appleButton}</>}<p className="mock-hint">Local mock mode: use code <strong>000000</strong>.</p></section></main>; }
