import { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/v1';
interface RecordData { party_name: string | null; amount: number | null; amount_frequency: string | null; key_date: string | null; }
interface Document { id: string; document_type: string; status: string; extracted_record: RecordData | null; }
interface VaultProps { onNavigateToUpload: () => void; onNavigateToDetail: (documentId: string) => void; }

const typeLabel: Record<string, string> = { auto_policy: 'Auto policy', home_policy: 'Home policy', life_insurance: 'Life insurance', warranty: 'Warranty', tax: 'Tax document', receipt: 'Receipt', other: 'Document' };
const typeIcon: Record<string, string> = { auto_policy: '▤', home_policy: '⌂', life_insurance: '◇', warranty: '✓', tax: '▥', receipt: '▧', other: '▤' };
function parseDocumentDate(date: string | null) { if (!date) return null; const parsed = new Date(date); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function daysUntil(date: string | null) { const parsed = parseDocumentDate(date); return parsed ? Math.ceil((parsed.getTime() - new Date(new Date().toDateString()).getTime()) / 86400000) : null; }
function formatDate(date: string | null) { const parsed = parseDocumentDate(date); return parsed ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(parsed) : null; }
function formatAmount(amount: number | null, frequency: string | null) { if (amount === null) return null; return `${new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(amount)}${frequency === 'annual' ? '/yr' : ''}`; }

export function Vault({ onNavigateToUpload, onNavigateToDetail }: VaultProps) {
  const { token } = useAuth(); const [documents, setDocuments] = useState<Document[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void fetchDocuments(); }, [token]);
  async function fetchDocuments() { try { setLoading(true); const response = await fetch(`${API_BASE_URL}/documents?limit=100`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(); const data = await response.json(); setDocuments(data.documents || []); setError(null); } catch { setError('We could not load your documents. Please try again.'); } finally { setLoading(false); } }
  const upcoming = documents.filter((d) => { const days = daysUntil(d.extracted_record?.key_date ?? null); return days !== null && days >= 0 && days <= 30; });
  function DocumentCard({ document, featured = false }: { document: Document; featured?: boolean }) { const record = document.extracted_record; const days = daysUntil(record?.key_date ?? null); const renewal = formatDate(record?.key_date ?? null); return <button className={`document-card ${featured ? 'featured' : ''}`} onClick={() => onNavigateToDetail(document.id)}><span className="document-icon">{typeIcon[document.document_type] ?? '▤'}</span><span className="document-copy"><strong>{typeLabel[document.document_type] ?? 'Document'}{record?.party_name ? ` · ${record.party_name}` : ''}</strong>{record?.amount !== null && record?.amount !== undefined && <span>{formatAmount(record.amount, record.amount_frequency)}</span>}{renewal && <span className="renewal-line">▣ Renews on {renewal}</span>}{document.status === 'parsing' && <span className="processing">Processing document…</span>}</span>{days !== null && <span className={`countdown ${days <= 7 ? 'urgent' : ''}`}>{featured ? `Renews in ${days} days` : `${days} days`}</span>}<span className="chevron" aria-hidden="true">›</span></button>; }
  return <main className="page-content"><header className="page-header"><div><p className="eyebrow">Your documents</p><h1>Vault</h1><p className="page-subtitle">Renewals and important details, in one calm place.</p></div><button className="button primary" onClick={onNavigateToUpload}>⇧ Upload document</button></header>{loading ? <p className="status-message">Loading your vault…</p> : error ? <div className="notice error">{error}<button className="text-button" onClick={() => void fetchDocuments()}>Try again</button></div> : documents.length === 0 ? <section className="empty-state"><span className="empty-icon">▤</span><h2>Your vault is ready</h2><p>Add your first document to track renewals and keep the important details close at hand.</p><button className="button primary" onClick={onNavigateToUpload}>Upload a document</button></section> : <><section className="vault-section">{upcoming.length > 0 && <><h2>Upcoming</h2><div className="document-list">{upcoming.map((document) => <DocumentCard key={`upcoming-${document.id}`} document={document} featured />)}</div></>}</section><section className="vault-section"><h2>All documents</h2><div className="document-list">{documents.map((document) => <DocumentCard key={document.id} document={document} />)}</div></section></>}</main>;
}
